server:
  port: 9000
  context-path: /water/demo

spring:
  redis:
    database: 0
    host: 192.168.1.12
    port: 6379
    password: zjtachao
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 100
      min-idle: 1